# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ahmed Gaber | Portfolio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ahmed Gaber (aigdonia) Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aigdonia.github.io" # the base hostname & protocol for your site
twitter_username: aigdonia
github_username:  aigdonia

# Build settings
markdown: kramdown
